workflows:
  build-android:
    name: Build on Mac mini M2
    environment:
      instance_type: mac_mini_m2  # ✅ Doğru alan budur
      os: macos
      shell: bash
      python: "3.10"
    scripts:
      - echo "🔧 Ortam hazırlanıyor..."
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install buildozer cython
      - buildozer android debug
    artifacts:
      - bin/*.apk
