workflows:
  build-android:
    name: Build Kivy App for Android
    environment:
      machine:
        os: linux
      vars:
        ANDROID_HOME: /opt/android-sdk
    scripts:
      - echo "Setting up Python environment"
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install cython buildozer
      - echo "Initializing Buildozer"
      - buildozer android debug
    artifacts:
      - bin/*.apk
