workflows:
  build-android:
    name: Build with Buildozer
    environment:
      os: linux
      python: "3.10"
    scripts:
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install buildozer cython
      - buildozer android debug
    artifacts:
      - bin/*.apk
