workflows:
  build-android:
    name: Build Android on mac_mini_m2
    environment:
      instance_type: mac_mini_m2
      os: macos
      shell: bash
      python: "3.10"
    scripts:
      - echo "🔧 Ortam hazırlanıyor..."
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install buildozer cython
      - echo "📦 Buildozer ile APK oluşturuluyor..."
      - buildozer android debug
    artifacts:
      - bin/*.apk
